### ISSUE TITLE
哥 有v吗？新手求解一下

### ISSUE THREAD

**Issue by ilikik** [yixiaolunhui/flutter_project#1]
呜呜呜呜，孩子太难了，没有main文件，咋运行的都不知道！！！

**Comment by yixiaolunhui** [comment]
v有的，dalong2008， 还有不好意思，项目中设定了不同环境的main文件，你可以点击其中一个如 main_qa,然后点击运行runapp方法

**Comment by yixiaolunhui** [comment]
![image](https://github.com/yixiaolunhui/flutter_project/assets/7698081/63893b3b-cc8f-4ee5-b123-cf5ad22780cc)
<img width="1127" alt="image" src="https://github.com/yixiaolunhui/flutter_project/assets/7698081/bf1ae465-8f9c-4629-b09f-276e59c256d4">
